type Query {
  question(page: Int! ) @http(
		method:GET,
		url: "http://localhost:3000/graphql"
	):![Question!]!

  answers @http(
		method:GET,
		url: "http://localhost:3000/graphql"
	): [Answer!]!

  userQuestion @http(
		method:POST,
		url: "http://localhost:3000/graphql"
	): [Question]!
}
